### ISSUE TITLE
Why changed_when false in the pre-run tasks?

### ISSUE THREAD

**Issue by janban-outlook** [LearnLinuxTV/personal_ansible_desktop_configs#3]
Just a small thing, but I am trying to understand every bit and piece of this approach.
I am wondering why you are using changed_when: False in the apt update task.
This means the result is always green, right? Whether the task did something or not.

**Comment by LearnLinuxTV** [comment]
The reason for this is because the apt repository index is literally always going to change, so reporting a change for this offers no value and instead just makes the entire thing show that something was updated, but only because an apt update was run.
