### ISSUE TITLE
Specific roles for a particular machine

### ISSUE THREAD

**Issue by janban-outlook** [LearnLinuxTV/personal_ansible_desktop_configs#4]
Hi Jay,

I really like this approach, and I am playing around with it to set up the configuration playbooks for my machines.
There is one thing that I am wondering, though.
In your approach you have two type of machines, the servers and the workstations. But what if you want to set up a particular machine with some specific tasks? 
I am trying to create a repository which I can use to recreate all machines in my network, including the ones that I have for specific tasks. For example, I have a VM that runs PiHole, and I have another VM as a plex media server. Following your example, these would both be server machines, and will keep their basic server configuration up to date. But they also have tasks that are very specific for their particular function. 
I was thinking of copying local.yml to pihole.yml and add the pihole playbook to it. Then I have to change the cron job for all machines to pull a $(hostname).yml instead of the default local.yml file. 
``` 
{ 
  ansible-pull -U -o <myrepo> $(hostname).yml 
} || { 
  ansible-pull -U -o <myrepo> 
}
```
If a hostname.yml exists, then that playbook will be run instead of the default local.yml.

Does this make sense? Or am I overlooking an easier approach?

Thanks for your examples and instructive videos, anyway!!

Jan

**Comment by ghost** [comment]
Hey Jan,

you could refer to the machines hostname for example:

- name: install apache webserver
   package:
     name:  apache2
     state: latest
   when:
     - "'www' in ansible_hostname"

So the play is only executed on hosts which have www in their hostname.


Regards,
Frank

**Comment by janban-outlook** [comment]
@ank0m , that makes sense.

Also, looking at local.yml, I can follow the same structure:

```
- hosts: server
  tags: server
  become: true
  roles:
    - server
   
- hosts: piholes
  become: true
  roles:
    - pihole
 ```

**Comment by janvanveldhuizen** [comment]
Okay, ready for testing !!  😂 🤓 

![image](https://user-images.githubusercontent.com/43573150/107887100-f1f6cb00-6f03-11eb-930d-f185a316ec93.png)

**Comment by gotmax23** [comment]
It's also possible to add the same host to multiple groups.

**Comment by LearnLinuxTV** [comment]
Sorry I missed this comment. The code as I have it already lets you do a per-machine config. That's what the host_vars file does, and that should give you everything needed for that. If you still haven't figured this out though, let me know!
