### ISSUE TITLE
Use FQCN instead of short module names in Ansible

### ISSUE THREAD

**Issue by alexs77** [LearnLinuxTV/personal_ansible_desktop_configs#6]
It's possible that modules use the same names for tasks. Because of that, Ansible suggests to use "FQCN". Eg. instead of `copy`, use `ansible.builtin.copy`.

PR #5 fixes this.

**Comment by LearnLinuxTV** [comment]
I appreciate you taking the time to add the pull request, but this particular repository is provided as a reference for a video I did and the code has to be the same as it is in the video. (Who knows, maybe an updated video will come out some day). Thank you so much though.
