### ISSUE TITLE
localhost do not match with host set all

### ISSUE THREAD

**Issue by pinkworld123** [LearnLinuxTV/personal_ansible_desktop_configs#7]
Hello I am getting this error while running ansible-pull, warning the implicit localhost does not match all

can you please help me to fix it? - hosts: all do not match the localhost and skipping any tasks. 

same applies for workstation hosts defined in hosts file. 

thanks for help.

**Comment by LearnLinuxTV** [comment]
As long as the hostname matches in /etc/hostname & /etc/hosts (on the actual system being configured by Ansible), and you also have a matching hostname in the inventory file as well as a host_vars file, then it should run fine. My best guess is one or more of those things is missing in your config.
