### ISSUE TITLE
Please add a license to this repository

### ISSUE THREAD

**Issue by gotmax23** [LearnLinuxTV/personal_ansible_desktop_configs#9]
Please add a license to this repository. Your code is not open source unless it has an open source license. Thanks!

**Comment by LearnLinuxTV** [comment]
Thank you for taking the time to write this in. However, I don't accept pull requests or issues on this particular repository - reason being, it's provided as reference for a video and isn't actually useful on its own. I really do appreciate you taking the time to submit that though, it shows great attention to detail on your part.

**Comment by gotmax23** [comment]
> However, I don't accept pull requests or issues on this particular repository - reason being, it's provided as reference for a video and isn't actually useful on its own.

Whether or not you accept pull requests, folks cannot legally incorporate the examples from this repository into their own setups without a license. This seems contrary to your reason for creating this repository in the first place.

**Comment by janban-outlook** [comment]
I think that is nonsense. Jay provided this code as a reference and example next to his video about this subject. He will be more than happy if we copy it and adjust it to our own needs.
